In [ ]:
from datetime import datetime
query = [{'transaction_type': 'redeemed', 'sender_id': 17, 'receiver_id': 13, 'amount': 9000.0, 'timestamp': '2025-12-05 17:05:28', 'transaction_id': None}, {'transaction_type': 'sent', 'sender_id': 13, 'receiver_id': 12, 'amount': 500.0, 'timestamp': '2025-12-05 17:05:08', 'transaction_id': 'D070D70'}, {'transaction_type': 'received', 'sender_id': 13, 'receiver_id': 12, 'amount': 500.0, 'timestamp': '2025-12-05 17:05:08', 'transaction_id': 'D070D70'}, {'transaction_type': 'redeemed', 'sender_id': 20, 'receiver_id': 13, 'amount': 15000.0, 'timestamp': '2025-12-05 17:04:55', 'transaction_id': None}, {'transaction_type': 'redeemed', 'sender_id': 20, 'receiver_id': 12, 'amount': 15000.0, 'timestamp': '2025-12-05 17:03:43', 'transaction_id': None}]
users = []

for user in query:
    if len(users) >= 3:  # stop after 3 entries
        break
    dt = datetime.strptime(user["timestamp"], "%Y-%m-%d %H:%M:%S")
    time = dt.strftime("%I:%M %p")
    diff = datetime.now() - dt
    days = diff.days
    minute = diff.seconds // 60

    if days == 0:
        time = time
    elif days == 1:
        time = f"Yesterday"
    else:
        time = f"{days} days ago"

    if user["transaction_type"] == "sent":
        users.append({
            "id" : user["sender_id"],
            "amount" : user["amount"],
            "time" : time
        })
    elif user["transaction_type"] == "redeemed":
        users.append({
            "id" : user["receiver_id"],
            "amount" : user["amount"],
            "time" : time
        })
    else:
        continue
    print(user)


{'transaction_type': 'redeemed', 'sender_id': 17, 'receiver_id': 13, 'amount': 9000.0, 'timestamp': '2025-12-05 17:05:28', 'transaction_id': None}
{'transaction_type': 'sent', 'sender_id': 13, 'receiver_id': 12, 'amount': 500.0, 'timestamp': '2025-12-05 17:05:08', 'transaction_id': 'D070D70'}
{'transaction_type': 'redeemed', 'sender_id': 20, 'receiver_id': 13, 'amount': 15000.0, 'timestamp': '2025-12-05 17:04:55', 'transaction_id': None}


{'transaction_type': 'sent', 'sender_id': 13, 'receiver_id': 12, 'amount': 500.0, 'timestamp': '2025-12-05 17:10:09', 'transaction_id': '2E4EE7E'}
{'transaction_type': 'redeemed', 'sender_id': 17, 'receiver_id': 13, 'amount': 9000.0, 'timestamp': '2025-12-05 17:05:28', 'transaction_id': None}
{'transaction_type': 'sent', 'sender_id': 13, 'receiver_id': 12, 'amount': 500.0, 'timestamp': '2025-12-05 17:05:08', 'transaction_id': 'D070D70'}